# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Global transparency and blur for all windows
windowrulev2 = opacity 0.80 0.40, class:.*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1
