#!/bin/bash

#####################################################################
# Apollo OS - Keyboard Shortcuts Display
# Copyright © 2025 by Manuel Kraibacher
#
# Description: Display all Apollo OS keyboard shortcuts in Rofi
# Usage: apollo-os-shortcuts.sh
#####################################################################

export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

shortcuts=(
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║               ⌨️   APOLLO OS KEYBOARD SHORTCUTS              ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║                      📱  ANWENDUNGEN                         ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
    "  Super + Return                      Terminal (Alacritty)"
    "  Super + K                           Terminal (Kitty)"
    "  Super + T                           Terminal (Ptyxis)"
    "  Super + Space                       App Launcher (Rofi)"
    "  Super + Shift + Space               Quick Menu"
    "  Super + D                           Dateimanager (Nautilus)"
    "  Super + N                           Texteditor"
    "  Super + B                           Browser (Firefox)"
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║                    🪟  FENSTERVERWALTUNG                      ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
    "  Super + Q                           Fenster schließen"
    "  Super + F                           Vollbild umschalten"
    "  Super + C                           Fenster zentrieren"
    "  Super + R                           Fensterbreite umschalten"
    "                                      (33% → 50% → 66% → 85% → 100%)"
    "  Super + Links/Rechts                Fokus wechseln"
    "  Super + Hoch/Runter                 Fokus hoch/runter"
    "  Super + Shift + Links/Rechts        Fenster verschieben"
    "  Super + Shift + Hoch/Runter         Fenster hoch/runter verschieben"
    "  Super + Alt + Links/Rechts          Spalte verschieben"
    "  Super + H / L                       Breite ändern"
    "  Super + J / K                       Höhe ändern"
    "  Super + Comma                       Spalten verbrauchen links"
    "  Super + Period                      Spalten ausstoßen rechts"
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║                      🖥️   WORKSPACES                          ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
    "  Super + 1-9                         Workspace wechseln"
    "  Super + Shift + 1-9                 Fenster zu Workspace"
    "  Super + Tab                         Nächster Workspace"
    "  Super + Shift + Tab                 Vorheriger Workspace"
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║                 📸  SCREENSHOT & AUFNAHME                     ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
    "  Print / Super + S                   Screenshot (Region + Editor)"
    "  Shift + Print                       Screenshot → Zwischenablage"
    "  Ctrl + Print                        Fullscreen Screenshot"
    "  Alt + Print                         Bildschirmaufnahme Start/Stop"
    "  Super + Print                       Color Picker"
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║                  🔵  BLUETOOTH & WLAN                         ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
    "  Super + Ctrl + B                    Bluetooth Manager (TUI)"
    "  Super + Ctrl + W                    WiFi Manager (TUI)"
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║                    🎤  SPRACHEINGABE                          ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
    "  Super + V                           Spracheingabe (Whisper)"
    "  Rechte Strg (halten)                Push-to-Talk"
    "  'Apollo' (Aktivierungswort)         Sprachassistent"
    "    → Apollo wie spät                 Uhrzeit vorlesen"
    "    → Apollo welcher tag              Datum vorlesen"
    "    → Apollo terminal                 Terminal öffnen"
    "    → Apollo browser                  Browser öffnen"
    "    → Apollo sperren                  Bildschirm sperren"
    "    → Apollo ruhemodus                System in Ruhemodus"
    "    → Apollo neustart                 System neustarten"
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║                    🎨  VISUAL MODE                            ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
    "  Super + Shift + V                   Visual Mode umschalten"
    "  Super + Shift + Space → Visual      Visual Mode Menü"
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║                    🎵  MEDIA & HELLIGKEIT                     ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
    "  Lautstärke +/-                      Audio lauter/leiser"
    "  Stumm-Taste                         Audio stumm"
    "  Mikrofon-Taste                      Mikrofon stumm"
    "  Helligkeit +/-                      Bildschirmhelligkeit"
    "  Play/Pause                          Medien Play/Pause"
    "  Vor/Zurück                          Nächster/Vorheriger Titel"
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║                        🔒  SYSTEM                             ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
    "  Super + L                           Bildschirm sperren"
    "  Super + Shift + E                   Abmelden"
    "  Super + X                           Power Menü"
    ""
    "╔══════════════════════════════════════════════════════════════╗"
    "║   💡  TIPP: Super + Shift + Space für das Quick Menu!        ║"
    "╚══════════════════════════════════════════════════════════════╝"
    ""
)

printf '%s\n' "${shortcuts[@]}" | rofi -dmenu -p "⌨️  Keyboard Shortcuts" -i \
    -theme-str 'window {width: 1050px; height: 750px;} listview {lines: 25; scrollbar: true;} element {padding: 5px 12px; font: "JetBrainsMono Nerd Font 11";}'
