#!/bin/bash

#####################################################################
# Apollo OS - Session Statistics
# Copyright © 2025 by Manuel Kraibacher
#
# Description: Display session statistics and system info
#####################################################################

set -e

CONFIG_DIR="$HOME/.config/apollo-os"
STATE_FILE="$CONFIG_DIR/daemon-state.json"
LOG_FILE="$CONFIG_DIR/daemon.log"

# Parse session info
if [ -f "$STATE_FILE" ] && command -v jq &>/dev/null; then
    startup_time_raw=$(jq -r '.startup_time' "$STATE_FILE" 2>/dev/null)
    if [ "$startup_time_raw" != "null" ] && [ -n "$startup_time_raw" ]; then
        startup_time=$(date -d "$startup_time_raw" "+%Y-%m-%d %H:%M:%S" 2>/dev/null || echo "Unknown")
    else
        startup_time="Unknown"
    fi
else
    startup_time="Unknown"
fi

# System info
session_uptime=$(uptime -p 2>/dev/null || echo "Unknown")
load_avg=$(uptime | awk -F'load average:' '{print $2}' | xargs)

# CPU usage
cpu_usage=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -d'%' -f1 2>/dev/null || echo "N/A")

# RAM usage
ram_total=$(free -h | grep Mem | awk '{print $2}')
ram_used=$(free -h | grep Mem | awk '{print $3}')
ram_percent=$(free | grep Mem | awk '{printf("%.1f", $3/$2 * 100.0)}')

# Disk usage
disk_usage=$(df -h / | tail -1 | awk '{print $5}')
disk_free=$(df -h / | tail -1 | awk '{print $4}')

# Battery info
if [ -f /sys/class/power_supply/BAT0/capacity ]; then
    battery=$(cat /sys/class/power_supply/BAT0/capacity)
    battery_status=$(cat /sys/class/power_supply/BAT0/status)
    battery_info="Battery: ${battery}% (${battery_status})"
else
    battery_info="Battery: N/A (Desktop)"
fi

# Window Manager
if pgrep -x niri >/dev/null; then
    wm_name="Niri (Apollo Orbit)"
elif pgrep -x sway >/dev/null; then
    wm_name="Sway (Apollo Grid)"
else
    wm_name="Unknown"
fi

# Profile & Theme
source "$CONFIG_DIR/config.env" 2>/dev/null || true
profile_info="Profile: ${DEFAULT_PROFILE:-unknown} | Theme: ${DEFAULT_THEME:-unknown}"

# AI Statistics
if [ -f "$LOG_FILE" ]; then
    gemini_calls=$(grep -c "Response generated by Gemini" "$LOG_FILE" 2>/dev/null || echo 0)
    ollama_calls=$(grep -c "Response generated by Ollama" "$LOG_FILE" 2>/dev/null || echo 0)
    total_ai_calls=$((gemini_calls + ollama_calls))
    
    if [ $total_ai_calls -gt 0 ]; then
        gemini_percent=$(awk "BEGIN {printf \"%.1f\", ($gemini_calls / $total_ai_calls) * 100}")
        ai_stats="AI Calls: ${total_ai_calls} (Gemini: ${gemini_calls} [${gemini_percent}%], Ollama: ${ollama_calls})"
    else
        ai_stats="AI Calls: 0 (No activity)"
    fi
    
    # Error count
    error_count=$(grep -c "\[ERROR\]" "$LOG_FILE" 2>/dev/null || echo 0)
    warning_count=$(grep -c "\[WARNING\]" "$LOG_FILE" 2>/dev/null || echo 0)
else
    ai_stats="AI Calls: N/A (Log not found)"
    error_count=0
    warning_count=0
fi

# Build statistics text
stats_text="━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Apollo OS - Session Statistics
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📅 Session Started: $startup_time
⏱️  Uptime: $session_uptime
⚙️  Load Average: $load_avg

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 System Resources
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🖥️  CPU Usage: ${cpu_usage}%
🧠 RAM: ${ram_used} / ${ram_total} (${ram_percent}%)
💾 Disk: ${disk_usage} used (${disk_free} free)
🔋 $battery_info

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Session Info
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🪟 Window Manager: $wm_name
🎨 $profile_info

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 AI Intelligence
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🤖 $ai_stats
⚠️  Warnings: $warning_count | Errors: $error_count

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Display with rofi
echo "$stats_text" | rofi -dmenu -p "Apollo OS Statistics" -mesg "Press ESC to close" -no-custom -lines 30 -width 50

# Alternative: Display in terminal
# echo "$stats_text"
