#!/usr/bin/env python3

"""
Apollo OS - Intelligence Daemon
Copyright © 2026 by Manuel Kraibacher

Description: Hybrid AI Engine with Gemini (Primary) + Ollama (Fallback)
Features:
  - System monitoring and notifications
  - Telegram integration
  - Interactive chat via Rofi
  - Time-based greetings and random interactions
"""

import os
import sys
import time
import json
import subprocess
import logging
import signal
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, Dict, Any
import threading

# Third-party imports
try:
    import google.generativeai as genai
    import psutil
    from telegram import Bot
    from telegram.error import TelegramError
except ImportError as e:
    print(f"ERROR: Missing required Python packages: {e}")
    print("Please install: pip3 install google-generativeai psutil python-telegram-bot")
    sys.exit(1)

# Configuration
CONFIG_FILE = Path.home() / ".config" / "apollo-os" / "config.env"
STATE_FILE = Path.home() / ".config" / "apollo-os" / "daemon-state.json"
LOG_FILE = Path.home() / ".config" / "apollo-os" / "daemon.log"

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger("apollo-daemon")


class ApolloConfig:
    """Apollo OS Configuration Manager"""

    def __init__(self):
        self.config = self.load_config()

    def load_config(self) -> Dict[str, str]:
        """Load configuration from env file"""
        config = {}

        if not CONFIG_FILE.exists():
            logger.error(f"Configuration file not found: {CONFIG_FILE}")
            return config

        with open(CONFIG_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    # Remove quotes
                    value = value.strip('"').strip("'")
                    config[key] = value

        return config

    def get(self, key: str, default: str = "") -> str:
        """Get configuration value"""
        return self.config.get(key, default)


class HybridAIEngine:
    """Hybrid AI Engine: Gemini (Primary) + Ollama (Fallback)"""

    def __init__(self, config: ApolloConfig):
        self.config = config
        self.gemini_available = False
        self.ollama_available = False

        # Initialize Gemini
        try:
            api_key = self.config.get('GEMINI_API_KEY')
            if api_key:
                genai.configure(api_key=api_key)
                self.gemini_model = genai.GenerativeModel(
                    self.config.get('GEMINI_MODEL', 'gemini-2.0-flash')
                )
                self.gemini_available = True
                logger.info("Gemini AI initialized successfully")
        except Exception as e:
            logger.warning(f"Failed to initialize Gemini: {e}")

        # Check Ollama availability
        self.check_ollama()

        # Preload Ollama model if configured
        if self.ollama_available and self.config.get('OLLAMA_PRELOAD') == 'true':
            self.preload_ollama()

    def check_ollama(self) -> bool:
        """Check if Ollama is available"""
        try:
            result = subprocess.run(
                ['ollama', 'list'],
                capture_output=True,
                timeout=5
            )
            self.ollama_available = result.returncode == 0
            if self.ollama_available:
                logger.info("Ollama is available")
            return self.ollama_available
        except Exception as e:
            logger.warning(f"Ollama not available: {e}")
            return False

    def preload_ollama(self):
        """Preload Ollama model into RAM"""
        model = self.config.get('OLLAMA_MODEL', 'qwen2.5:0.5b')
        try:
            logger.info(f"Preloading Ollama model: {model}")
            subprocess.run(
                ['ollama', 'run', model, '--keepalive', '24h', ''],
                capture_output=True,
                timeout=30
            )
            logger.info("Ollama model preloaded")
        except Exception as e:
            logger.warning(f"Failed to preload Ollama: {e}")

    def generate(self, prompt: str, context: str = "") -> Optional[str]:
        """Generate response using Hybrid AI with graceful fallback"""

        full_prompt = f"{context}\n\n{prompt}" if context else prompt

        # Try Gemini first
        if self.gemini_available:
            try:
                response = self.gemini_model.generate_content(full_prompt)
                logger.info("Response generated by Gemini")
                return response.text
            except Exception as e:
                logger.warning(f"Gemini failed: {e}, falling back to Ollama")

        # Fallback to Ollama
        if self.ollama_available:
            try:
                model = self.config.get('OLLAMA_MODEL', 'qwen2.5:0.5b')
                result = subprocess.run(
                    ['ollama', 'run', model, full_prompt],
                    capture_output=True,
                    text=True,
                    timeout=30
                )
                if result.returncode == 0:
                    logger.info("Response generated by Ollama")
                    return result.stdout.strip()
            except Exception as e:
                logger.error(f"Ollama failed: {e}")

        # Both failed - return generic fallback messages (GRACEFUL DEGRADATION)
        logger.warning("Both AI engines unavailable, using fallback response")
        
        # Simple keyword-based fallback responses
        fallback_responses = {
            'greeting_morning': "Good morning! Welcome back to Apollo OS.",
            'greeting_evening': "Good evening! Hope you had a productive day.",
            'random': "All systems operational. Everything running smoothly.",
            'default': "System message acknowledged."
        }
        
        # Detect intent from prompt
        prompt_lower = prompt.lower()
        if 'morning' in prompt_lower or 'greeting' in prompt_lower:
            if 'morning' in prompt_lower:
                return fallback_responses['greeting_morning']
            elif 'evening' in prompt_lower:
                return fallback_responses['greeting_evening']
            else:
                return "Hello! Welcome back."
        elif 'humor' in prompt_lower or 'fun' in prompt_lower or 'flux' in prompt_lower:
            return fallback_responses['random']
        else:
            return fallback_responses['default']


class SystemMonitor:
    """System monitoring and notifications"""

    def __init__(self):
        self.thresholds = {
            'battery_low': 20,
            'battery_critical': 10,
            'disk_warning': 85,
            'ram_warning': 85
        }
        self.last_notifications = {}

    def should_notify(self, key: str, cooldown_minutes: int = 30) -> bool:
        """Check if enough time has passed since last notification"""
        if key not in self.last_notifications:
            return True

        elapsed = datetime.now() - self.last_notifications[key]
        return elapsed > timedelta(minutes=cooldown_minutes)

    def mark_notified(self, key: str):
        """Mark that a notification was sent"""
        self.last_notifications[key] = datetime.now()

    def check_battery(self) -> Optional[Dict[str, Any]]:
        """Check battery status"""
        if not hasattr(psutil, "sensors_battery"):
            return None

        battery = psutil.sensors_battery()
        if not battery:
            return None

        status = {
            'percent': battery.percent,
            'plugged': battery.power_plugged,
            'time_left': battery.secsleft if not battery.power_plugged else None
        }

        # Check for alerts
        if not battery.power_plugged:
            if battery.percent <= self.thresholds['battery_critical']:
                if self.should_notify('battery_critical'):
                    status['alert'] = f"⚠️ Critical battery: {battery.percent}%"
                    self.mark_notified('battery_critical')
                    # Voice warning (if available)
                    try:
                        subprocess.run(['apollo-speak', 'battery_critical'], 
                                     check=False, timeout=5, 
                                     stdout=subprocess.DEVNULL, 
                                     stderr=subprocess.DEVNULL)
                    except:
                        pass
            elif battery.percent <= self.thresholds['battery_low']:
                if self.should_notify('battery_low'):
                    status['alert'] = f"🔋 Low battery: {battery.percent}%"
                    self.mark_notified('battery_low')
                    # Voice warning (if available)
                    try:
                        subprocess.run(['apollo-speak', 'battery_low'], 
                                     check=False, timeout=5,
                                     stdout=subprocess.DEVNULL, 
                                     stderr=subprocess.DEVNULL)
                    except:
                        pass

        return status

    def check_disk(self) -> Optional[Dict[str, Any]]:
        """Check disk usage"""
        disk = psutil.disk_usage('/')
        status = {
            'percent': disk.percent,
            'free_gb': disk.free / (1024**3)
        }

        if disk.percent >= self.thresholds['disk_warning']:
            if self.should_notify('disk_warning'):
                status['alert'] = f"💾 Disk space low: {disk.percent}% used"
                self.mark_notified('disk_warning')

        return status

    def check_ram(self) -> Optional[Dict[str, Any]]:
        """Check RAM usage"""
        ram = psutil.virtual_memory()
        status = {
            'percent': ram.percent,
            'available_gb': ram.available / (1024**3)
        }

        if ram.percent >= self.thresholds['ram_warning']:
            if self.should_notify('ram_warning'):
                status['alert'] = f"🧠 High RAM usage: {ram.percent}%"
                self.mark_notified('ram_warning')

        return status

    def get_system_info(self) -> str:
        """Get comprehensive system information"""
        battery = self.check_battery()
        disk = self.check_disk()
        ram = self.check_ram()

        info = []

        if battery:
            plugged = "🔌 Plugged" if battery['plugged'] else "🔋 On battery"
            info.append(f"Battery: {battery['percent']}% ({plugged})")

        if disk:
            info.append(f"Disk: {disk['percent']}% used ({disk['free_gb']:.1f} GB free)")

        if ram:
            info.append(f"RAM: {ram['percent']}% used ({ram['available_gb']:.1f} GB available)")

        return "\n".join(info)


class TelegramNotifier:
    """Telegram notification handler"""

    def __init__(self, config: ApolloConfig):
        self.enabled = False
        self.bot = None
        self.chat_id = None

        try:
            token = config.get('TELEGRAM_BOT_TOKEN')
            chat_id = config.get('TELEGRAM_USER_ID')

            if token and chat_id:
                self.bot = Bot(token=token)
                self.chat_id = chat_id
                self.enabled = True
                logger.info("Telegram notifications enabled")
        except Exception as e:
            logger.warning(f"Failed to initialize Telegram: {e}")

    def send(self, message: str) -> bool:
        """Send Telegram notification"""
        if not self.enabled:
            return False

        try:
            self.bot.send_message(chat_id=self.chat_id, text=message)
            logger.info("Telegram notification sent")
            return True
        except TelegramError as e:
            logger.error(f"Failed to send Telegram: {e}")
            return False


class ApolloNotification:
    """Desktop notification manager"""

    @staticmethod
    def send(title: str, message: str, urgency: str = "normal", icon: str = "dialog-information",
             action: str = None, action_label: str = "Reply"):
        """Send desktop notification with optional action"""
        try:
            cmd = [
                'notify-send',
                '-u', urgency,
                '-i', icon,
                title,
                message
            ]

            # Add action if specified (for interactive notifications)
            if action:
                cmd.extend([
                    '-A', f'{action_label}={action}'
                ])

            subprocess.run(cmd)
            logger.info(f"Notification sent: {title}")
        except Exception as e:
            logger.error(f"Failed to send notification: {e}")

    @staticmethod
    def send_interactive(title: str, message: str, urgency: str = "normal"):
        """Send interactive notification that opens chat on click"""
        try:
            # Use dunstify if available for better action support
            if subprocess.run(['which', 'dunstify'], capture_output=True).returncode == 0:
                subprocess.run([
                    'dunstify',
                    '-u', urgency,
                    '-i', 'face-smile',
                    '-A', 'reply,Reply',
                    title,
                    message
                ], capture_output=True, text=True)
            else:
                # Fallback: Send notification and rely on manual chat opening
                ApolloNotification.send(title, f"{message}\n(Click to reply via 'apollo-os-chat')",
                                      urgency=urgency, icon='face-smile')

            logger.info(f"Interactive notification sent: {title}")
        except Exception as e:
            logger.error(f"Failed to send interactive notification: {e}")


class ApolloDaemon:
    """Main Apollo OS Daemon"""

    def __init__(self):
        self.config = ApolloConfig()
        self.ai = HybridAIEngine(self.config)
        self.monitor = SystemMonitor()
        self.telegram = TelegramNotifier(self.config)
        self.running = True
        self.state = self.load_state()

        # Setup signal handlers
        signal.signal(signal.SIGTERM, self.shutdown)
        signal.signal(signal.SIGINT, self.shutdown)

        logger.info("Apollo Daemon initialized")

    def load_state(self) -> Dict:
        """Load daemon state"""
        if STATE_FILE.exists():
            try:
                with open(STATE_FILE, 'r') as f:
                    return json.load(f)
            except Exception as e:
                logger.warning(f"Failed to load state: {e}")

        return {
            'last_greeting': None,
            'last_random_message': None,
            'startup_time': datetime.now().isoformat()
        }

    def save_state(self):
        """Save daemon state"""
        try:
            STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
            with open(STATE_FILE, 'w') as f:
                json.dump(self.state, f, indent=2)
        except Exception as e:
            logger.error(f"Failed to save state: {e}")

    def shutdown(self, signum, frame):
        """Graceful shutdown"""
        logger.info("Shutting down Apollo Daemon...")
        self.running = False
        self.save_state()
        sys.exit(0)

    def send_greeting(self):
        """Send time-based greeting"""
        now = datetime.now()
        hour = now.hour

        # Check if already greeted today
        last_greeting = self.state.get('last_greeting')
        if last_greeting:
            last_time = datetime.fromisoformat(last_greeting)
            if last_time.date() == now.date():
                return  # Already greeted today

        # Determine greeting based on time
        if 5 <= hour < 12:
            greeting_type = "morning"
        elif 18 <= hour < 23:
            greeting_type = "evening"
        else:
            return  # No greeting during other times

        # Generate greeting with AI (ENGLISH ONLY)
        prompt = f"Generate a friendly {greeting_type} greeting for the user. Keep it short (1-2 sentences) and natural. Use English only."
        response = self.ai.generate(prompt)

        if response:
            ApolloNotification.send_interactive("Apollo OS", response)
            self.telegram.send(f"🌅 {response}")
            self.state['last_greeting'] = now.isoformat()
            self.save_state()

    def send_random_message(self):
        """Send random fun message"""
        last_random = self.state.get('last_random_message')
        if last_random:
            last_time = datetime.fromisoformat(last_random)
            elapsed = datetime.now() - last_time
            if elapsed < timedelta(hours=4):
                return  # Too soon

        # ENGLISH ONLY
        prompt = "Generate a short, humorous system message like 'The flux capacitor is running smoothly' or 'All systems nominal, captain'. Be creative and fun. Use English only."
        response = self.ai.generate(prompt)

        if response:
            ApolloNotification.send_interactive("Apollo OS", response)
            self.state['last_random_message'] = datetime.now().isoformat()
            self.save_state()

    def monitor_system(self):
        """Monitor system and send alerts"""
        battery = self.monitor.check_battery()
        if battery and 'alert' in battery:
            ApolloNotification.send("System Alert", battery['alert'], urgency="critical")
            self.telegram.send(battery['alert'])

        disk = self.monitor.check_disk()
        if disk and 'alert' in disk:
            ApolloNotification.send("System Alert", disk['alert'], urgency="normal")
            self.telegram.send(disk['alert'])

        ram = self.monitor.check_ram()
        if ram and 'alert' in ram:
            ApolloNotification.send("System Alert", ram['alert'], urgency="normal")

    def run(self):
        """Main daemon loop"""
        logger.info("Apollo Daemon started")

        # Send startup notification
        self.telegram.send("🚀 Apollo OS started")

        iteration = 0
        while self.running:
            try:
                # Every 60 seconds: Monitor system
                if iteration % 60 == 0:
                    self.monitor_system()

                # Every 30 minutes: Check for greetings
                if iteration % 1800 == 0:
                    self.send_greeting()

                # Every 4 hours: Random message
                if iteration % 14400 == 0 and iteration > 0:
                    self.send_random_message()

                iteration += 1
                time.sleep(1)

            except Exception as e:
                logger.error(f"Error in main loop: {e}")
                time.sleep(5)


def main():
    """Entry point"""
    daemon = ApolloDaemon()
    daemon.run()


if __name__ == "__main__":
    main()
